---
loki:
  enabled: true
  persistence:
    enabled: true
    storageClass: managed-nfs-storage
    size: 1Gi

promtail:
  enabled: true

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true

prometheus:
  enabled: true
  persistence:
    enabled: true
    storageClass: managed-nfs-storage
    size: 1Gi
