---
name: Lint and Test

on:
  pull_request:
    paths-ignore:
      - README.md

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: ./
          yamllint_strict: false
          yamllint_comment: true
          yamllint_config_filepath: .github/.yamllint
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  install-test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.24.0@sha256:8e3b1732d8d1e8b4f74c60d3504abf8472b6884d930d2f14013818cd9ff3f7e2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.1
      - name: Create KIND cluster
        uses: helm/kind-action@v1.3.0
        with:
          config: .github/kind.yaml
          node_image: "kindest/node:${{ matrix.k8s }}"

      - name: Test OTel helm install
        run: |-
          cat > opentelemetry/endpoint.yaml << EOL
          ---
          config:
          exporters:
            prometheusremotewrite:
              endpoint: https://localhost/api/prom/push
            loki:
              endpoint: "https://localhost/loki/api/v1/push"
          EOL

          helm repo add opentelemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo update opentelemetry
          helm upgrade --install \
            otel-agent opentelemetry/opentelemetry-collector \
            -n opentelemetry --create-namespace \
            --values opentelemetry/agent.yaml \
            --values opentelemetry/endpoints.yaml
